


-- 스테이징에서 실행
SELECT
    B.PT_NM
   ,B.PT_RRN
  FROM TEMPSIRL_LIST3 B
WHERE 1=1
 AND B.SRIL_CFMT_NO ='Y'
GROUP BY PT_NM,PT_RRN

MINUS

SELECT
   PT_NM
   ,PT_RRN
  FROM TEMPSIRL_LIST3  A
WHERE 1=1
  AND SRIL_CFMT_NO !='Y'
  AND EXISTS
		(SELECT
		   B.PT_NM
		   ,B.PT_RRN
  		FROM TEMPSIRL_LIST3 B
		WHERE 1=1
 		  AND B.SRIL_CFMT_NO ='Y'
 		  AND B.PT_NM = A.PT_NM
 		  AND B.PT_RRN = A.PT_RRN
		GROUP BY PT_NM,PT_RRN
		)


;;;



SELECT DISTINCT HOSP_NO,WRT_DT,WRT_NM,HLTH_INS_ETPS_NM,HLTH_INSC_NO,PT_NM,PT_RRN,SRIL_CFMT_NO,APY_STR_DT --,(SELECT Z.PT_NO FROM PCTPCPAM Z WHERE UPPER(Z.PT_NM) = PT_NM AND Z.PT_RRN = PLS_ENCRYPT_B64_ID(PT_RRN,800)) AS PT_NO
  FROM TEMPSIRL_LIST3
WHERE APY_STR_DT IS NOT NULL
  AND SRIL_CFMT_NO ='Y'
  AND (PT_NM,PT_RRN) IN
(SELECT B.PT_NM,B.PT_RRN
  FROM TEMPSIRL_LIST3 B
WHERE 1=1
 AND B.SRIL_CFMT_NO ='Y'
GROUP BY PT_NM,PT_RRN
MINUS
SELECT PT_NM,PT_RRN
  FROM TEMPSIRL_LIST3  A
WHERE 1=1
  AND SRIL_CFMT_NO !='Y'
  AND EXISTS
(SELECT B.PT_NM,B.PT_RRN
  FROM TEMPSIRL_LIST3 B
WHERE 1=1
 AND B.SRIL_CFMT_NO ='Y'
 AND B.PT_NM = A.PT_NM
 AND B.PT_RRN = A.PT_RRN
GROUP BY PT_NM,PT_RRN
)
)

;;;
