
/*이재강 책임님*/
EXEC :COMN_GRP_CD_NM := '진료기록';

SELECT B.COMN_GRP_CD_NM, A.*
  FROM CCCCCSTE A
     , (SELECT COMN_GRP_CD, COMN_GRP_CD_NM
          FROM CCCCCLTC
         WHERE COMN_GRP_CD_NM LIKE '%'|| :COMN_GRP_CD_NM ||'%') B

 WHERE A.COMN_GRP_CD IN B.COMN_GRP_CD
 ORDER BY A.COMN_GRP_CD, A.SCRN_MRK_SEQ;


 /**/

