
-- 오브젝트 조회
SELECT *
  FROM ALL_SOURCE
 WHERE UPPER(TEXT) LIKE '%SDK_SMS_SEND%'
   AND OWNER IN ('HSMS','ISMS','XBIL')
;
-- EQS
SELECT *
  FROM FXQUERYSTORE
 WHERE (UPPER(QUERYTEXT) LIKE '%SDK_SMS_SEND%'
   OR UPPER(QUERYTEXT) LIKE '%SDK_SMS_REPORT%')
   AND QUERYID LIKE '%PA%'
;


-- 이런 컬럼
SDK_SMS_SEND , SDK_SMS_SEND_REPORT
-- 혹은 이런 컬럼명을
HSMS.SDK_SMS_SEND@CALL_SMS  OR  SDK_SMS_SEND   OR    HSMS.SDK_SMS_SEND    OR  HSMS.SDK_SMS_SEND@CALL_SMS    @CALL_SMS2
-- 이렇게 바꿔라
=>  ISMS.SDK_SMS_SEND
