


SELECT
 PT_RRN
 , PLS_DECRYPT_B64_ID(PT_RRN,800)

FROM PCTPCPAM
WHERE PT_NO = '01745906'
;
SELECT
 PT_RRN
 , PLS_DECRYPT_B64_ID(PT_RRN,800)

FROM PCTPCPAM
WHERE PT_NO = '01490690'
;

SELECT
SUBSTR(PLS_DECRYPT_B64_ID(APCT_RRN, 800),1,6)||'-'||SUBSTR(PLS_DECRYPT_B64_ID(APCT_RRN, 800),7,1)||'******' AS APCT_RRN
, NVL(APCT_RRN,'NULL')
FROM ACPETHCD
WHERE PT_NO = '01745906';



CASE WHEN B.PT_RRN IS NULL THEN '-'
         ELSE SUBSTR(B.PT_RRN,0,6) || '-' || SUBSTR(B.PT_RRN,7,1) || '******'
    END                                                                       AS PT_RRN

     ;

SELECT
CASE WHEN (A.APCT_RRN IS NULL AND B.PT_RRN IS NULL) THEN '-'
     WHEN B.PT_RRN IS NULL THEN SUBSTR(A.APCT_RRN,1,6)||'-'||SUBSTR(A.APCT_RRN,7,1)||'******'
     ELSE SUBSTR(B.PT_RRN,1,6)||'-'||SUBSTR(B.PT_RRN,7,1)||'******'
     END AS APCT_RRN

FROM ACPETHCD A
    ,PCTPCPAM B
WHERE A.PT_NO = B.PT_NO(+)
   AND A.PT_NO = '01490690'
