SELECT DEPT_CD, DEPT_NM FROM PDEDBMSM WHERE DEPT_NM LIKE '%과';


/* 과별 수납 정보 */
SELECT A.RPY_PACT_ID,
       A.MED_DEPT_CD,
       B.DEPT_NM,
       COUNT(*)
FROM ACPPEOPD A          /* 외래수납정보 */
     ,PDEDBMSM B
WHERE A.PT_NO LIKE NVL(:MY_PT_NO,'%')
   AND B.DEPT_CD = A.MED_DEPT_CD(+)
GROUP BY RPY_PACT_ID,MED_DEPT_CD,B.DEPT_NM ;
