
EXEC :MY_PT_NO :='01741540' ;
EXEC :MY_RPY_PACT_ID := '';


SELECT
SETL_APBT_ID	--AS "SETL_APBT_ID    결제승인ID"
,CARD_SETL_SEQ	AS "CARD_SETL_SEQ   카드결제순번"
,RPY_DT	AS "RPY_DT  수납일자"
,PT_NO	--AS "PT_NO   환자번호"
,HSP_TP_CD	AS "HSP_TP_CD   병원구분코드"
,MED_ORD_DTM	AS "MED_ORD_DTM 진료처방일시"
,ORD_EXPT_DTM	AS "ORD_EXPT_DTM    처방예정일시"
,RPY_CLS_CD	AS "RPY_CLS_CD  수납유형코드"
,RPY_SEQ	AS "RPY_SEQ 수납순번"
,CRCMP_KND_CD	AS "CRCMP_KND_CD    카드사구분코드"
,CARD_NO	AS "CARD_NO 카드번호"
,CARD_APBT_NO	AS "CARD_APBT_NO    카드승인번호"
,APBT_DTM	AS "APBT_DTM    승인일시"
,CARD_ISTM_MNS_TP_CD	AS "CARD_ISTM_MNS_TP_CD 카드할부개월구분코드"
,RCP_NO	AS "RCP_NO  영수증번호"
,PACT_TP_CD	AS "PACT_TP_CD  원무접수구분코드"
,CNCL_DTM	AS "CNCL_DTM    취소일시"
,RPY_STF_NO	AS "RPY_STF_NO  수납직원번호"
,TRML_IP_ADDR	AS "TRML_IP_ADDR    단말기IP주소"
,CARD_AVL_DT	AS "CARD_AVL_DT 카드유효일자"
,CARD_SETL_AMT	AS "CARD_SETL_AMT   카드결제금액"
,CARD_TRML_NO	AS "CARD_TRML_NO    카드단말기번호"
,CARD_NM	AS "CARD_NM 카드명"
,CARD_SGNT_CNTE	AS "CARD_SGNT_CNTE  카드서명내용"
,TRD_IHRT_NO	AS "TRD_IHRT_NO 거래고유번호"
,CARD_CMSN_AMT	AS "CARD_CMSN_AMT   카드수수료금액"
,AFLT_NO	AS "AFLT_NO 가맹점번호"
,INET_RPY_CARD_APBT_NO	AS "INET_RPY_CARD_APBT_NO   인터넷수납카드승인번호"
,EXRT	AS "EXRT    환율"
,OOC_CRNC_AMT	AS "OOC_CRNC_AMT    본국화폐금액"
,FRCT_CRNC_UNIT_NM	AS "FRCT_CRNC_UNIT_NM   화폐단위코드"
,HPCD_USE_YN	AS "HPCD_USE_YN 하이패스카드사용여부"
,BOBD_PT_NO	AS "BOBD_PT_NO  합본이전환자번호"
,BIND_DTM	AS "BIND_DTM    합본일시"
,BIND_STF_NO	AS "BIND_STF_NO 합본직원번호"
,FSR_STF_NO	AS "FSR_STF_NO  최초등록직원번호"
,FSR_DTM	AS "FSR_DTM 최초등록일시"
,FSR_PRGM_NM	AS "FSR_PRGM_NM 최초등록프로그램명"
,FSR_IP_ADDR	AS "FSR_IP_ADDR 최초등록IP주소"
,LSH_STF_NO	AS "LSH_STF_NO  최종변경직원번호"
,LSH_DTM	AS "LSH_DTM 최종변경일시"
,LSH_PRGM_NM	AS "LSH_PRGM_NM 최종변경프로그램명"
,LSH_IP_ADDR	AS "LSH_IP_ADDR 최종변경IP주소"
,TKN_NO	AS "TKN_NO  토큰번호"
,RPY_PACT_ID	AS "RPY_PACT_ID 수납원무접수ID"
,RPY_CLS_SEQ	AS "RPY_CLS_SEQ 수납유형순번"
,NCOR_TP_CD	AS "NCOR_TP_CD  밴사구분코드"
,MOB_SETL_YN	AS "MOB_SETL_YN 모바일결제여부"
,TRD_TP_CD	AS "TRD_TP_CD   거래구분코드"
	FROM ACPPECPE /* 카드수납상세 */
WHERE PT_NO LIKE NVL(:MY_PT_NO,'%')
 AND SETL_APBT_ID LIKE NVL(:MY_RPY_PACT_ID,'%')
ORDER BY 1,2,3,5,4;


EXEC :MY_PT_NO :='01741540' ;
EXEC :MY_RPY_PACT_ID := '';
-- 순환기 내과 : 9시20분 테스트 0008141120

