EXEC :IN_OWNER      := UPPER('hbil');
EXEC :IN_TABLE_NAME := UPPER('apoprsvt');

SELECT C.COMMENTS COMMENTS_TAB
--     , A.COLUMN_ID
--     , A.OWNER
     , A.TABLE_NAME
     , A.COLUMN_NAME
     , A.DATA_TYPE
     , B.COMMENTS COMMENTS_COL

     , A.DATA_LENGTH
     , DECODE(A.NULLABLE, 'N', 'Y', NULL) NOTNULL


  FROM ALL_TAB_COLUMNS@DL_ORAMIG A
     , ALL_COL_COMMENTS@DL_ORAMIG B
     , ALL_TAB_COMMENTS@DL_ORAMIG C



 WHERE A.TABLE_NAME = :IN_TABLE_NAME
   AND A.OWNER      = :IN_OWNER
   AND A.OWNER      = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.COLUMN_NAME= B.COLUMN_NAME
   AND A.TABLE_NAME = C.TABLE_NAME
   AND A.OWNER = C.OWNER
 ORDER BY COLUMN_ID












;


<!-- 김재강 책임님 아끼는 쿼리 -->
EXEC :IN_OWNER      := UPPER('hbil');
EXEC :IN_TABLE_NAME := UPPER('apoprsvt');

SELECT C.COMMENTS COMMENTS_TAB
     , A.COLUMN_ID
     , A.OWNER
     , A.TABLE_NAME
     , A.COLUMN_NAME
     , B.COMMENTS COMMENTS_COL
     , A.DATA_TYPE
     , A.DATA_LENGTH
     , DECODE(A.NULLABLE, 'N', 'Y', NULL) NOTNULL
  FROM ALL_TAB_COLUMNS@DL_ORAMIG A
     , ALL_COL_COMMENTS@DL_ORAMIG B
     , ALL_TAB_COMMENTS@DL_ORAMIG C
 WHERE A.TABLE_NAME = :IN_TABLE_NAME
   AND A.OWNER      = :IN_OWNER
   AND A.OWNER      = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.COLUMN_NAME= B.COLUMN_NAME
   AND A.TABLE_NAME = C.TABLE_NAME
   AND A.OWNER = C.OWNER
 ORDER BY COLUMN_ID

