



EXEC :IN_OWNER      := 'HBIL';
EXEC :IN_TABLE_NAME := 'ACPPRODM';

SELECT C.TABLE_NAME
     , C.COMMENTS
--     , CASE
--           WHEN ROWNUM = 1 THEN 'NULL AS ' || RPAD(A.COLUMN_NAME, 30, ' ') || ' -- ' || LPAD( TO_CHAR(A.COLUMN_ID), 3, '0') || '. ' || B.COMMENTS
--           ELSE '     , NULL AS ' || RPAD(A.COLUMN_NAME, 30, ' ') || ' -- ' || LPAD( TO_CHAR(A.COLUMN_ID), 3, '0') || '. ' || B.COMMENTS
--       END   AS ABC
--     , A.COLUMN_ID
     , A.COLUMN_NAME

     , A.DATA_TYPE
     , B.COMMENTS
     , (CASE WHEN A.DATA_TYPE LIKE '%CHAR%' THEN A.DATA_LENGTH END) AS LENGTH
     , (SELECT 'Y'
          FROM ALL_CONSTRAINTS AA
             , ALL_CONS_COLUMNS BB


         WHERE AA.TABLE_NAME = A.TABLE_NAME
           AND AA.CONSTRAINT_TYPE ='P'
           AND AA.OWNER = BB.OWNER
           AND AA.CONSTRAINT_NAME = BB.CONSTRAINT_NAME
           AND BB.COLUMN_NAME = A.COLUMN_NAME)  PK
     , DECODE(NULLABLE, 'N', 'Y') NOTNULL
  FROM ALL_TAB_COLUMNS A
     , ALL_COL_COMMENTS B
     , ALL_TAB_COMMENTS C
 WHERE A.TABLE_NAME = :IN_TABLE_NAME
   AND A.OWNER      = :IN_OWNER
   AND A.OWNER      = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.COLUMN_NAME= B.COLUMN_NAME
   AND A.OWNER = C.OWNER
   AND A.TABLE_NAME = C.TABLE_NAME
 ORDER BY COLUMN_ID