 SELECT C.TABLE_NAME
     , C.COMMENTS
     , 1 UNION1
     --, '     , NULL AS ' || RPAD(A.COLUMN_NAME, 30, ' ') || ' -- ' || LPAD( TO_CHAR(A.COLUMN_ID), 3, '0') || '. ' || B.COMMENTS
     ,  A.COLUMN_ID
     , A.COLUMN_NAME
     , B.COMMENTS
     , A.DATA_TYPE
     , (CASE WHEN A.DATA_TYPE LIKE '%CHAR%' THEN A.DATA_LENGTH END) AS LENGTH
     , (SELECT 'Y'
          FROM ALL_CONSTRAINTS AA
             , ALL_CONS_COLUMNS BB
         WHERE AA.TABLE_NAME = A.TABLE_NAME
           AND AA.CONSTRAINT_TYPE ='P'
           AND AA.OWNER = BB.OWNER
           AND AA.CONSTRAINT_NAME = BB.CONSTRAINT_NAME
           AND BB.COLUMN_NAME =A.COLUMN_NAME)  PK
     , DECODE(NULLABLE, 'N', 'Y') NULLABLE
  FROM ALL_TAB_COLUMNS A
     , ALL_COL_COMMENTS B
     , ALL_TAB_COMMENTS C
 WHERE A.TABLE_NAME = 'ACPPRPTD'
   AND A.OWNER      = 'HBIL'
   AND A.OWNER      = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.COLUMN_NAME= B.COLUMN_NAME
   AND A.OWNER = C.OWNER
   AND A.TABLE_NAME = C.TABLE_NAME
 ORDER BY COLUMN_ID;
