UPDATE INTO

;

UPDATE TABLE_NAME
SET COLUMN1 = VALUE1, COLUMN2 = VALUE2, ...
WHERE CONDITION;




;;


SELECT *
FROM ACPETHCD WHERE ROWNUM < 10;


-- ---------------------------------------------------------
EXEC :IN_OWNER      := UPPER('HBIL');
EXEC :IN_TABLE_NAME := UPPER('APOPRSVT');

SELECT C.COMMENTS COMMENTS_TAB
--     , A.COLUMN_ID
--     , A.OWNER
     , A.TABLE_NAME
     , A.COLUMN_NAME
     , A.DATA_TYPE
     , B.COMMENTS COMMENTS_COL

     , A.DATA_LENGTH
     , DECODE(A.NULLABLE, 'N', 'Y', NULL) NOTNULL


  FROM ALL_TAB_COLUMNS@DL_ORAMIG A
     , ALL_COL_COMMENTS@DL_ORAMIG B
     , ALL_TAB_COMMENTS@DL_ORAMIG C



 WHERE A.TABLE_NAME = :IN_TABLE_NAME
   AND A.OWNER      = :IN_OWNER
   AND A.OWNER      = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.COLUMN_NAME= B.COLUMN_NAME
   AND A.TABLE_NAME = C.TABLE_NAME
   AND A.OWNER = C.OWNER
 ORDER BY COLUMN_ID


