

SELECT
   BB.SID AS SID
   ,BB.STF_NO
   ,BB.KOR_NM
   ,BB.RRN
   ,BB.JICP_DT
   ,BB.RTRM_DT
   ,BB.BLNG_DEPT_CD
   ,BB.LST_SCHL_NM
   ,BB.LST_SCRR_GRDT_YMD

 FROM(
SELECT * FROM (
SELECT SID, COUNT(*) CNTT FROM
(

SELECT
*
FROM (SELECT
*
FROM (SELECT
   --STF_NO
   KOR_NM AS KKKKOR_NM
   --,SID
   ,COUNT(*) CNT
FROM PDESMSAM
GROUP BY
--STF_NO,
SID,
KOR_NM
)
WHERE CNT > 1
) A , PDESMSAM B
 WHERE A.KKKKOR_NM(+) = B.KOR_NM
    AND A.CNT IS NOT NULL
    AND B.RTRM_DT IS NULL

ORDER BY A.CNT ASC ,A.KKKKOR_NM DESC

)
GROUP BY SID
)    WHERE CNTT > 1
 ) AA ,PDESMSAM BB
 WHERE AA.SID(+) = BB.SID
 AND AA.CNTT IS NOT NULL
 AND BB.RTRM_DT IS NULL
ORDER BY AA.CNTT , BB.KOR_NM



;;;
SELECT KOR_NM, 
   RANK() OVER (ORDER BY KOR_NM DESC) AS RANK FROM
(
SELECT
   A.STF_NO
   ,A.KOR_NM
   ,(SELECT COUNT(STF_NO) AS CNT FROM PDESMSAM B WHERE A.STF_NO = B.STF_NO AND A.KOR_NM = B.KOR_NM)  AS NO_CNT
   ,(SELECT COUNT(KOR_NM) AS CNT FROM PDESMSAM B WHERE A.STF_NO = B.STF_NO AND A.KOR_NM = B.KOR_NM)  AS NM_CNT
FROM
   PDESMSAM A
--WHERE
   --NO_CNT > 1
   --NM_CNT > 1
GROUP BY A.STF_NO,A.KOR_NM

) GROUP BY KOR_NM
